Revert "kpatch: deprecate the replace command"
This partially reverts the following commit (except the changes in Readme,
which are OK):
-----------
commit 8e8de4718d8c13626f1010ec2851cb292a67f447
Author: Josh Poimboeuf <jpoimboe@redhat.com>
Date:   Mon Nov 16 09:38:38 2015 -0600

    kpatch: deprecate the replace command

    "kpatch replace" is complex, buggy, and probably unnecessary.  And
    upstream livepatch has nothing like it.

    Remove it from the kpatch utility, but leave the infrastructure in place
    in the patch module and the core module for now.

    Fixes: #456
-----------

'kpatch replace' is crucial when one mostly uses cumulative patches, i.e.
the patches that provide all the needed fixes in a single patch module.

It is very important to update such patches safely. That is, either the
new patch should be active after the update (if it succeeds) or the old one
should be used (if the update fails). Unloading of the old patch and then
loading the new one is more fragile because loading could fail and the
system would be left without patches at all.

The recommended workaround was to make sure the newer patch is a superset
of the old one. To be exact, the set of functions changed by the newer patch
should include all the functions changed by the older one. This is not
always possible even when one does not remove fixes from the patch.

By the way, "atomic replace" has been proposed for livepatch as well:
https://lkml.org/lkml/2018/2/6/152

The only issue with 'kpatch replace' I know about at the moment is
https://github.com/dynup/kpatch/issues/456:
"hook unload function doesn't run when module is replaced".

The current implementation of "atomic replace" for livepatch has the same
issue, by the way. It seems, it is difficult to resolve properly at the
kernel side. However, if the patches need load/unload hooks (callbacks),
we could probably design these callbacks in our cumulative patched according
to the current behaviour of Kpatch/livepatch core. Then, upgrade of our
patches would work properly. Downgrade (replacement with a previous version)
could be implemented as unload + load, it should be a rare operation anyway.

diff --git a/kpatch/kpatch b/kpatch/kpatch
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -49,6 +49,7 @@ usage () {
 	echo >&2
 	usage_cmd "load --all" "load all installed patch modules into the running kernel"
 	usage_cmd "load <module>" "load patch module into the running kernel"
+	usage_cmd "replace <module>" "load patch module into the running kernel, replacing all other modules"
 	usage_cmd "unload --all" "unload all patch modules from the running kernel"
 	usage_cmd "unload <module>" "unload patch module from the running kernel"
 	echo >&2
@@ -280,6 +281,7 @@ wait_for_patch_transition() {
 
 load_module () {
 	local module="$1"
+	local module_param="$2"
 
 	if ! core_loaded; then
 		if modprobe -q kpatch; then
@@ -321,7 +323,7 @@ load_module () {
 	echo "loading patch module: $module"
 	local i=0
 	while true; do
-		out="$(LC_ALL=C insmod "$module" 2>&1)"
+		out="$(LC_ALL=C insmod "$module" "$module_param" 2>&1)"
 		[[ -z "$out" ]] && break
 		echo "$out" 1>&2
 		[[ ! "$out" =~ "Device or resource busy" ]] &&
@@ -393,6 +395,14 @@ unload_module () {
 	rmmod "$PATCH" 2> /dev/null || return 0
 }
 
+unload_disabled_modules() {
+	for module in /sys/kernel/kpatch/patches/*; do
+		if [[ $(cat $module/enabled) -eq 0 ]]; then
+			unload_module $(basename $module) || die "failed to unload $module"
+		fi
+	done
+}
+
 get_module_version() {
 	MODVER="$(modinfo -F vermagic "$1")" || return 1
 	MODVER="${MODVER/ */}"
@@ -422,6 +432,14 @@ case "$1" in
 		load_module "$MODULE" || die "failed to load module $PATCH"
 		;;
 	esac
+	;;
+
+"replace")
+	[[ "$#" -ne 2 ]] && usage
+	PATCH="$2"
+	find_module "$PATCH" || die "can't find $PATCH"
+	load_module "$MODULE" replace=1 || die "failed to load module $PATCH"
+	unload_disabled_modules || die "failed to unload old modules"
 	;;
 
 "unload")
