Use atomic replace only when upgrading official cumulative patches
Atomic replacement of the binary patches results in non-obvious
behaviour w.r.t. patch/unpatch callbacks (hooks in the "old" kpatch).
That is, when patch1 is atomically replaced with patch2, the unpatch
callbacks from patch1 will not be called. It looks like this will remain
this way, see the details below:

* for the "old" kpatch: https://github.com/dynup/kpatch/issues/456
* for livepatch: https://lkml.org/lkml/2018/1/31/642

We do need atomic replace in ReadyKernel and we might need patch/unpatch
callbacks in some patches. Without the guarantee that unpatch callbacks
will be called, we'll have to be careful when using them. If these
callbacks are used to clean up something that other callbacks have done,
the last patch to unload must do all cleaning up. This should work if we
are only replacing our cumulative ReadyKernel patch with a newer
version and that version is aware of all previous versions, what is
needed to clean up there. However, things become rather difficult if we
try to downgrade the patch (the older patch is unlikely to know what
needs cleaning up for the newer patch) or when dealing with some
unifficial or non-cumulative patches (for the same reason as for
downgrade).

To sort out this mess somehow, I have rewritten "kpatch replace" command
so that atomic replace will only be used to replace an official
cumulative ReadyKernel patch with a newer version. This is the most
common case and if we decide to use callbacks in ReadyKernel patches, we
will be able to design these callbacks accordingly.

In all other cases, atomic replace is not used, the previous patches are
disabled first, then the new patch is loaded normally. The unpatch callbacks
will be called for the previous patches, then patch callbacks will be
called for the new patch. This should be OK.

So, "kpatch replace" now works as follows:

1. If one tries to use "kpatch replace" to load a non-official or a
non-cumulative patch  (this is currently detected by the names of
patch modules), all currently loaded patches are disabled first. Then
the new patch is loaded normally.

2. If one tries to load an official cumulative patch, all loaded patches
except the official cumulative patches with smaller version-release are
disabled first. Then atomic replace is used.

If the new patch fails to load, the previously disabled patches will
remain disabled. If it was not a patch upgrade operation, the system
would end up having no active binary patches at all. Far from ideal but
the risk seems acceptable. Downgrade and operations with non-official
patches should be rare anyway.

I reiterate: if the patch is upgraded, everything should work as
before. If "kpatch replace" succeeds, the new patch will be loaded and
active. Otherwise the older patch will remain loaded and active.

By the way, all this complexity indicates that we should consider using
callbacks in the most important fixes only and only if there is no other
acceptable way to provide a fix.

Done in the scope of https://jira.sw.ru/browse/PSBM-79803.

diff --git a/kpatch/kpatch b/kpatch/kpatch
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -436,8 +436,97 @@ unload_module () {
 	return 0
 }
 
+is_cumulative_patch() {
+	echo "$1" | grep -q -E '^kpatch_cumulative_[0-9_]+_r[0-9]+$'
+}
+
+is_enabled() {
+	[[ -f "$SYSFS/$1/enabled" ]] && [[ $(cat "$SYSFS/$1/enabled") -ne 0 ]]
+}
+
+# $1 >= $2
+version_gte() {
+	[  "$1" = "$(echo -e "$1\n$2" | sort -rV | head -n1)" ]
+}
+
+# (version, release) of $1 >= (version, release) of $2
+verrel_gte() {
+	VER_EXPR='s/^kpatch_cumulative_([0-9_]+)_r[0-9]+$/\1/;s/_/./g'
+	REL_EXPR='s/^kpatch_cumulative_[0-9_]+_r([0-9]+)$/\1/'
+
+	local ver1=$(echo $1 | sed -r "$VER_EXPR")
+	local rel1=$(echo $1 | sed -r "$REL_EXPR")
+	local ver2=$(echo $2 | sed -r "$VER_EXPR")
+	local rel2=$(echo $2 | sed -r "$REL_EXPR")
+
+	if [[ "$ver1" == $ver2 ]]; then
+		[[ $rel1 -ge $rel2 ]]
+	else
+		version_gte $ver1 $ver2
+	fi
+}
+
+
+replace_module () {
+	local new_module="$1"
+	local modname="$(get_module_name "$1")"
+	local bname=""
+
+	local log_event_prev="$LOG_EVENT"
+	LOG_EVENT="REPLACE"
+	LOG_PATCH="$modname"
+
+	is_enabled "$modname" && die "module $modname is already loaded and enabled"
+
+	if ! is_cumulative_patch "$modname"; then
+		# Trying to load a patch which is not an official cumulative
+		# patch. One cannot be sure the patch will play nicely with
+		# the callbacks defined in the currently loaded patches,
+		# so atomic replace is not used here. Instead, disable all
+		# the loaded patches first and then load the new one.
+		# If loading fails, the previously loaded patches will
+		# remain disabled. Not very good but acceptable: the new
+		# patch is not official anyway.
+		for module in "$SYSFS"/*; do
+			bname=$(basename $module)
+			if is_enabled "$bname"; then
+				disable_patch "$bname" || die "failed to disable $bname"
+			fi
+		done
+		load_module "$new_module" || die "failed to load module $PATCH"
+		LOG_EVENT="$log_event_prev"
+		return
+	fi
+
+	# Trying to load an official cumulative patch. Disable all
+	# non-official and non-cumulative patches first for the same
+	# reasons: we cannot tell if the callbacks from the patches clash.
+	# Same for the loaded official cumulative patches that have a higher
+	# version than this one (i.e., handle downgrade).
+	#
+	# Again, if loading of the patch fails after this, the previously
+	# loaded patches may remain disabled except for the earlier versions
+	# of the official cumulative patches. Not ideal but OK.
+	for module in "$SYSFS"/*; do
+		bname=$(basename $module)
+		if is_cumulative_patch "$bname"; then
+			if verrel_gte "$bname" "$modname" && is_enabled "$bname"; then
+				disable_patch "$bname" || die "failed to disable $bname"
+			fi
+			continue
+		fi
+
+		if is_enabled "$bname"; then
+			disable_patch "$bname" || die "failed to disable $bname"
+		fi
+	done
+
+	load_module "$new_module" replace=1 || die "failed to load module $PATCH"
+	LOG_EVENT="$log_event_prev"
+}
+
 unload_disabled_modules() {
-	for module in /sys/kernel/kpatch/patches/*; do
+	for module in "$SYSFS"/*; do
 		if [[ $(cat $module/enabled) -eq 0 ]]; then
 			unload_module $(basename $module) || die "failed to unload $module"
 		fi
@@ -479,7 +568,7 @@ case "$1" in
 	[[ "$#" -ne 2 ]] && usage
 	PATCH="$2"
 	find_module "$PATCH" || die "can't find $PATCH"
-	load_module "$MODULE" replace=1 || die "failed to load module $PATCH"
+	replace_module "$MODULE"
 	unload_disabled_modules || die "failed to unload old modules"
 	;;
 
